### ISSUE TITLE
`compgen` completions tracking issue

### ISSUE THREAD

**Issue by JoshMcguigan** [JoshMcguigan/shell_completion#1]
The `compgen` shell built-in provides helper methods for returning completions. Presently, `shell_completion` provides a naive implementation of only a small fraction of the completions provided by `compgen`. This issue tracks progress toward `shell_completion` achieving feature parity.

[source of compgen functionality](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html)

- [ ] alias - Alias names
- [ ] arrayvar - Array variable names
- [ ] binding - Readline key binding names
- [ ] builtin - Names of shell builtin commands
- [ ] command - Command names
- [ ] directory - Directory names (an incomplete implementation of this exists within `shell_completion)
- [ ] disabled - Names of disabled shell builtins
- [ ] enabled - Names of enabled shell builtins
- [ ] export - Names of exported shell variables
- [ ] file - File names (an incomplete implementation of this exists within `shell_completion)
- [ ] function - Names of shell functions
- [ ] group - Group names
- [ ] helptopic - Help topics as accepted by the help builtin
- [ ] hostname - Hostnames, as taken from the file specified by the HOSTFILE shell variable
- [ ] job - Job names, if job control is active
- [ ] keyword - Shell reserved words
- [ ] running - Names of running jobs, if job control is active
- [ ] service - Service names
- [ ] setopt - Valid arguments for the -o option to the set builtin
- [ ] shopt - Shell option names as accepted by the shop builtin
- [ ] signal - Signal names
- [ ] stopped - Names of stopped jobs, if job control is active
- [ ] user - User names
- [ ] variable - Names of all shell variables

Pull requests adding any of the above would be very much appreciated. Feel free to reach out in this issue thread if you have any questions about how to get started.
